/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

import { FileBase, FileBaseOptions, IResolver } from "projen";
import { NodeProject } from "projen/lib/javascript";

export interface UpgradeVulnerableTransitivesScriptFileOptions
  extends FileBaseOptions {
  /** Minutes a release must be published before it may be installed. */
  readonly minimumReleaseAgeMinutes: number;
  /** Severity floor, matching the `auditDeps` gate this exists to satisfy. */
  readonly auditLevel: string;
}

/**
 * Bumps transitive packages that carry an advisory.
 *
 * `pnpm update` only re-resolves the packages it is named, and the generated
 * upgrade task names direct dependencies only -- so a transitive package stays
 * pinned even with a patch in range, while `auditDeps` reddens every build on it
 * (undici GHSA-rfgv-xxqx-mfg5, all 31 repos). Naming the direct parent does not
 * help, and nor does `--depth Infinity` on that list: the vulnerable package has
 * to be named itself. Taking the names from the audit keeps `package.json`
 * untouched, which a bare `pnpm update` would not.
 */
export class UpgradeVulnerableTransitivesScriptFile extends FileBase {
  protected readonly options: UpgradeVulnerableTransitivesScriptFileOptions;

  constructor(
    project: NodeProject,
    options: UpgradeVulnerableTransitivesScriptFileOptions
  ) {
    super(project, "scripts/upgrade-vulnerable-transitives.js", options);
    this.options = options;
  }

  protected synthesizeContent(resolver: IResolver): string | undefined {
    const { minimumReleaseAgeMinutes, auditLevel } = resolver.resolve(
      this.options
    ) as UpgradeVulnerableTransitivesScriptFileOptions;

    return `
/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */
// ~~ Generated by projen. To modify, edit the @cdktn/provider-project source.
const { execFileSync } = require("child_process");

const AUDIT_LEVEL = "${auditLevel}";
const MINIMUM_RELEASE_AGE = "${minimumReleaseAgeMinutes}";

function pnpm(args, opts = {}) {
  return execFileSync("pnpm", args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    ...opts,
  });
}

// A clean audit still returns an empty advisories object and exit 0, so a missing
// one means the audit itself did not run -- not that nothing is flagged.
function vulnerablePackages() {
  let raw;
  try {
    raw = pnpm(["audit", "--audit-level", AUDIT_LEVEL, "--json"]);
  } catch (e) {
    // audit exits non-zero exactly when it finds something; stdout still has it.
    raw = e.stdout;
  }
  let advisories;
  try {
    advisories = JSON.parse(raw).advisories;
  } catch {
    advisories = undefined;
  }
  if (typeof advisories !== "object" || advisories === null) {
    // Surfaced, not swallowed -- but not fatal either, or one unreadable audit
    // would cost every other bump in the run. The audit gate still fails the build.
    console.error(
      "::warning::could not read 'pnpm audit --json'; flagged transitives were NOT refreshed"
    );
    return undefined;
  }
  return [
    ...new Set(
      Object.values(advisories)
        .map((a) => a.module_name)
        .filter(Boolean)
    ),
  ].sort();
}

function main() {
  const names = vulnerablePackages();
  // undefined means the audit was unreadable, which is not the same as clean and
  // has already been warned about.
  if (names === undefined) return;
  if (names.length === 0) {
    console.log("no " + AUDIT_LEVEL + "+ advisories to resolve");
    return;
  }

  console.log("attempting to resolve advisories in: " + names.join(", "));
  try {
    // --depth Infinity is what lets a transitive package be named at all.
    pnpm(
      [
        "update",
        ...names,
        "--depth",
        "Infinity",
        "--config.minimum-release-age=" + MINIMUM_RELEASE_AGE,
      ],
      { stdio: "inherit" }
    );
  } catch {
    // The only patch may still be inside the cooldown (pnpm raises
    // ERR_PNPM_NO_MATURE_MATCHING_VERSION). That is the cooldown working -- do not
    // fail the upgrade and lose every other bump with it.
    console.error(
      "::warning::could not upgrade " +
        names.join(", ") +
        " within the cooldown; lockfile unchanged"
    );
  }
}

main();
`;
  }
}
