/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

import { FileBase, FileBaseOptions, IResolver } from "projen";
import { NodeProject } from "projen/lib/javascript";

export interface UpgradeVulnerableTransitivesScriptFileOptions
  extends FileBaseOptions {
  /** Minutes a release must be published before it may be installed. */
  readonly minimumReleaseAgeMinutes: number;
  /** Severity floor, matching the `auditDeps` gate this exists to satisfy. */
  readonly auditLevel: string;
}

/**
 * Bumps transitive packages that carry an advisory.
 *
 * `pnpm update` only re-resolves the packages it is given, and the generated
 * upgrade task names direct dependencies only -- so a transitive package stays
 * pinned in the lockfile forever, even with a patch in range. Naming the direct
 * parent does not help, and neither does `--depth Infinity` on that list: the
 * vulnerable package has to be named itself.
 *
 * Meanwhile `auditDeps` fails the build on exactly those advisories, so a
 * transitive CVE turns every build in the fleet red with no automated way out.
 * undici GHSA-rfgv-xxqx-mfg5 did that to all 31 provider repos; brace-expansion
 * did it before that, and was patched by hand in cdktn-repository-manager.
 *
 * This asks the audit which packages are implicated and names those, which keeps
 * `package.json` untouched -- a bare `pnpm update` would rewrite declared ranges,
 * including turning the deliberate `constructs` upper bound into a caret.
 */
export class UpgradeVulnerableTransitivesScriptFile extends FileBase {
  protected readonly options: UpgradeVulnerableTransitivesScriptFileOptions;

  constructor(
    project: NodeProject,
    options: UpgradeVulnerableTransitivesScriptFileOptions
  ) {
    super(project, "scripts/upgrade-vulnerable-transitives.js", options);
    this.options = options;
  }

  protected synthesizeContent(resolver: IResolver): string | undefined {
    const { minimumReleaseAgeMinutes, auditLevel } = resolver.resolve(
      this.options
    ) as UpgradeVulnerableTransitivesScriptFileOptions;

    return `
/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */
// ~~ Generated by projen. To modify, edit the @cdktn/provider-project source.
const { execFileSync } = require("child_process");

const AUDIT_LEVEL = "${auditLevel}";
const MINIMUM_RELEASE_AGE = "${minimumReleaseAgeMinutes}";

function pnpm(args, opts = {}) {
  return execFileSync("pnpm", args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    ...opts,
  });
}

function vulnerablePackages() {
  let raw;
  try {
    raw = pnpm(["audit", "--audit-level", AUDIT_LEVEL, "--json"]);
  } catch (e) {
    // pnpm audit exits non-zero precisely when it finds something, so the
    // payload we want is on stdout of the "failure".
    raw = e.stdout;
  }
  if (!raw) return [];
  try {
    const advisories = JSON.parse(raw).advisories ?? {};
    return [
      ...new Set(
        Object.values(advisories)
          .map((a) => a.module_name)
          .filter(Boolean)
      ),
    ].sort();
  } catch {
    // A pnpm that cannot produce the JSON shape we expect must not take the
    // whole upgrade down -- the audit gate will still report the advisory.
    console.error("could not parse 'pnpm audit --json' output; skipping");
    return [];
  }
}

const names = vulnerablePackages();
if (names.length === 0) {
  console.log("no " + AUDIT_LEVEL + "+ advisories to resolve");
  process.exit(0);
}

console.log("attempting to resolve advisories in: " + names.join(", "));
try {
  // --depth Infinity is what lets a transitive package be named at all.
  pnpm(
    [
      "update",
      ...names,
      "--depth",
      "Infinity",
      "--config.minimum-release-age=" + MINIMUM_RELEASE_AGE,
    ],
    { stdio: "inherit" }
  );
} catch {
  // The only patched version may still be inside the cooldown, which pnpm
  // reports as ERR_PNPM_NO_MATURE_MATCHING_VERSION. That is the cooldown doing
  // its job, not a reason to fail the upgrade and lose every other bump with it.
  console.error(
    "could not upgrade " +
      names.join(", ") +
      " within the cooldown; leaving the lockfile alone"
  );
}
`;
  }
}
